---
title: "ELeFHAnt"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ELeFHAnt}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, results = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=10,
  fig.height=10
)
```

```{r setup}
library(ELeFHAnt)
```

```{r Read Data}
data("reference_PBMC")
data("query_PBMC")
reference = reference_PBMC
query = query_PBMC
query = NormalizeData(query)
query = FindVariableFeatures(query)
query = ScaleData(query)
query = RunPCA(query)
query = RunUMAP(query, dims = 1:20)
```

```{r Celltype Annotation}
###### Downsample is set to FALSE as number of cells in reference / query have already been downsampled ########
out.CelltypeAnnotation = CelltypeAnnotation(reference = reference, query = query, downsample = FALSE, classification.method = "Ensemble", validatePredictions = FALSE)
query$Celltypes = out.CelltypeAnnotation$PredictedCelltype_UsingEnsemble
p1 = DimPlot(out.CelltypeAnnotation, group.by = "seurat_clusters", label = T, reduction = "umap", label.size = 6, repel = T) + NoLegend()
p2 = DimPlot(out.CelltypeAnnotation, group.by = "PredictedCelltype_UsingEnsemble", label = T, reduction = "umap", label.size = 6, repel = T) + NoLegend()
p1+p2
```

```{r Label Harmonization}
###### Downsample is set to FALSE as number of cells in reference / query have already been downsampled ########
out.LabelHarmonization = LabelHarmonization(seurat.objects = c(reference, query), perform_integration = TRUE, downsample = FALSE, classification.method = "Ensemble", validatePredictions = FALSE)
p1 = DimPlot(out.LabelHarmonization, group.by = "Celltypes", label = T, label.size = 6, repel = T) + NoLegend()
p2 = DimPlot(out.LabelHarmonization, group.by = "HarmonizedLabels_UsingEnsemble", label = T, label.size = 6, repel = T) + NoLegend()
p1+p2
```

```{r Deduce Relationship}
###### Downsample is set to FALSE as number of cells in reference / query have already been downsampled ########
query_DR = query
query_DR$Celltypes = query$seurat_clusters
out.DR = DeduceRelationship(reference1 = reference, reference2 = query_DR, downsample = FALSE, classification.method = "Ensemble")
out.DR
```

```{r Benchmark ELeFHAnt}
###### Downsample is set to FALSE as number of cells in reference / query have already been downsampled ########
out.Benchmark = BenchmarkELeFHAnt(reference = reference, query = query, downsample = FALSE)
p1 = DimPlot(out.Benchmark, group.by = "PredictedCelltype_UsingEnsemble", label=T, repel = T, label.size = 6) + NoLegend() + ggtitle("ELeFHAnt Predictions")
p2 = DimPlot(out.Benchmark, group.by = "predicted.id", label=T, repel = T, label.size = 6) + NoLegend() + ggtitle("LabelTransfer Predictions")
p3 = DimPlot(out.Benchmark, group.by = "scpred_prediction", label=T, repel = T, label.size = 6) + NoLegend() + ggtitle("scPred Predictions")
p1+p2+p3
```
